name: Deploy wolf-blank (stage)

on:
  push:
    branches:
      - stage

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Pull repository on server
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: ${{ secrets.SSH_PORT }}
          script: |
            cd /home/sys-admin/staging.wolfthemes.com/wp-content/themes/wolf-blank
            git fetch origin ${{ github.ref_name }}
            git checkout ${{ github.ref_name }}
            git pull --ff-only origin ${{ github.ref_name }}
